name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v2
        
      - name: Build & Test
        uses: MrRamych/gradle-actions/openjdk-8@3.1
        with:
          args: check
